### ISSUE TITLE
Training Problem

### ISSUE THREAD

**Issue by XiaoBuL** [lgcnsai/PS-KD-Pytorch#2]
Hello, what is the machine configuration trained in this article? I train on my machine: the Resnet18 network structure of CIFAR100 in the environment of Nvidia 2080 and pytorch1.6 can only achieve an accuracy of 78.600.

**Comment by lgcnsai** [comment]
Hello,
All experiments were performed on NVIDIA DGX-1 (V100) system with PyTorch on Multi-nodes with Multi-GPUs.
We verified reproducing PS-KD accuracy of 79.15 on ResNet18.
